/**
 * Curated professional-English content for role-based Lucid lessons.
 *
 * The catalogue favours language that professionals can use naturally in a
 * meeting, update, or written recommendation. Domain terms that are important
 * to understand but less suitable for general use are marked `recognition`.
 */

export const PROFESSIONAL_ROLE_IDS = [
  "finance-accounting",
  "project-product",
  "technology-engineering",
  "sales-business-development",
  "people-human-resources",
  "consulting-strategy",
  "operations-supply-chain",
  "healthcare",
] as const;

export type RoleId = (typeof PROFESSIONAL_ROLE_IDS)[number];
export type ProfessionalRoleId = RoleId;

export const SENIORITY_LEVEL_IDS = [
  "early-career",
  "experienced-contributor",
  "manager",
  "senior-leader",
  "executive",
] as const;

export type SeniorityId = (typeof SENIORITY_LEVEL_IDS)[number];
export type SeniorityLevelId = SeniorityId;

export const COMMUNICATION_GOAL_IDS = [
  "clarify",
  "align",
  "influence",
  "recommend",
  "negotiate",
  "challenge-diplomatically",
  "coach",
  "reassure",
] as const;

export type GoalId = (typeof COMMUNICATION_GOAL_IDS)[number];
export type CommunicationGoalId = GoalId;

export type SituationId =
  | "finance:month-end-close"
  | "finance:variance-review"
  | "finance:budget-forecast"
  | "finance:audit-discussion"
  | "project:roadmap-prioritisation"
  | "project:scope-change"
  | "project:stakeholder-update"
  | "project:delivery-retrospective"
  | "technology:architecture-review"
  | "technology:incident-response"
  | "technology:code-review"
  | "technology:technical-interview"
  | "sales:discovery-call"
  | "sales:proposal-pitch"
  | "sales:objection-handling"
  | "sales:pipeline-review"
  | "people:performance-conversation"
  | "people:hiring-interview"
  | "people:team-conflict"
  | "people:organisational-change"
  | "consulting:problem-framing"
  | "consulting:client-readout"
  | "consulting:executive-recommendation"
  | "consulting:workshop-facilitation"
  | "operations:capacity-planning"
  | "operations:supplier-negotiation"
  | "operations:process-improvement"
  | "operations:disruption-response"
  | "healthcare:patient-handover"
  | "healthcare:case-conference"
  | "healthcare:consent-discussion"
  | "healthcare:service-escalation";

export type ProfessionalSituationId = SituationId;

export type VocabularyPartOfSpeech =
  | "noun"
  | "verb"
  | "adjective"
  | "adverb"
  | "noun phrase"
  | "verb phrase";

export type ProfessionalDifficulty = "upper-b2" | "c1";
export type ProfessionalUsefulness = "essential" | "high" | "specialist";
export type LearningMode = "active" | "recognition";

export type ProfessionalRole = {
  id: RoleId;
  label: string;
  shortLabel: string;
  description: string;
  situations: readonly ProfessionalSituation[];
  defaultGoalIds: readonly GoalId[];
};

export type SeniorityLevel = {
  id: SeniorityLevelId;
  label: string;
  description: string;
  communicationFocus: string;
};

export type CommunicationGoal = {
  id: CommunicationGoalId;
  label: string;
  outcome: string;
  coachingPrompt: string;
};

export type ProfessionalSituation = {
  id: SituationId;
  roleId: RoleId;
  label: string;
  description: string;
  goalIds: readonly CommunicationGoalId[];
};

export type ProfessionalWord = {
  id: string;
  term: string;
  partOfSpeech: VocabularyPartOfSpeech;
  pronunciation: string;
  meaning: string;
  difficulty: ProfessionalDifficulty;
  usefulness: ProfessionalUsefulness;
  learningMode: LearningMode;
  roles: readonly RoleId[];
  situations: readonly SituationId[];
  seniority: readonly SeniorityId[];
  goals: readonly GoalId[];
  collocations: readonly string[];
  example: string;
  whenToUse: string;
  avoidOrMisuse: string;
  mission: string;
};

export type ProfessionalVocabularyEntry = ProfessionalWord;

export type ProfessionalWordFilters = {
  roleId?: RoleId;
  situationId?: SituationId;
  seniorityId?: SeniorityId;
  goalId?: GoalId;
  difficulty?: ProfessionalDifficulty;
  usefulness?: ProfessionalUsefulness;
  learningMode?: LearningMode;
};

export type ProfessionalVocabularyFilters = ProfessionalWordFilters;

type ProfessionalRoleDefinition = Omit<ProfessionalRole, "situations"> & {
  situationIds: readonly SituationId[];
};

const professionalRoleDefinitions: readonly ProfessionalRoleDefinition[] = [
  {
    id: "finance-accounting",
    label: "Finance & Accounting",
    shortLabel: "Finance",
    description: "Reporting performance, protecting financial integrity, and explaining commercial implications.",
    situationIds: [
      "finance:month-end-close",
      "finance:variance-review",
      "finance:budget-forecast",
      "finance:audit-discussion",
    ],
    defaultGoalIds: ["clarify", "recommend", "challenge-diplomatically"],
  },
  {
    id: "project-product",
    label: "Project & Product Management",
    shortLabel: "Project / Product",
    description: "Setting priorities, managing delivery choices, and keeping stakeholders aligned on outcomes.",
    situationIds: [
      "project:roadmap-prioritisation",
      "project:scope-change",
      "project:stakeholder-update",
      "project:delivery-retrospective",
    ],
    defaultGoalIds: ["align", "influence", "negotiate"],
  },
  {
    id: "technology-engineering",
    label: "Technology & Engineering",
    shortLabel: "Technology",
    description: "Explaining technical choices, managing operational risk, and collaborating on robust systems.",
    situationIds: [
      "technology:architecture-review",
      "technology:incident-response",
      "technology:code-review",
      "technology:technical-interview",
    ],
    defaultGoalIds: ["clarify", "recommend", "challenge-diplomatically"],
  },
  {
    id: "sales-business-development",
    label: "Sales & Business Development",
    shortLabel: "Sales",
    description: "Discovering customer needs, communicating value, and progressing commercial relationships.",
    situationIds: [
      "sales:discovery-call",
      "sales:proposal-pitch",
      "sales:objection-handling",
      "sales:pipeline-review",
    ],
    defaultGoalIds: ["influence", "negotiate", "reassure"],
  },
  {
    id: "people-human-resources",
    label: "HR & People Leadership",
    shortLabel: "People",
    description: "Supporting performance, resolving sensitive issues, and creating fair employee experiences.",
    situationIds: [
      "people:performance-conversation",
      "people:hiring-interview",
      "people:team-conflict",
      "people:organisational-change",
    ],
    defaultGoalIds: ["coach", "reassure", "challenge-diplomatically"],
  },
  {
    id: "consulting-strategy",
    label: "Consulting & Strategy",
    shortLabel: "Consulting",
    description: "Structuring ambiguous problems, building evidence, and presenting concise recommendations.",
    situationIds: [
      "consulting:problem-framing",
      "consulting:client-readout",
      "consulting:executive-recommendation",
      "consulting:workshop-facilitation",
    ],
    defaultGoalIds: ["clarify", "recommend", "influence"],
  },
  {
    id: "operations-supply-chain",
    label: "Operations & Supply Chain",
    shortLabel: "Operations",
    description: "Maintaining flow, improving reliability, and coordinating practical responses to disruption.",
    situationIds: [
      "operations:capacity-planning",
      "operations:supplier-negotiation",
      "operations:process-improvement",
      "operations:disruption-response",
    ],
    defaultGoalIds: ["align", "negotiate", "reassure"],
  },
  {
    id: "healthcare",
    label: "Healthcare",
    shortLabel: "Healthcare",
    description: "Communicating clinical information clearly, coordinating care, and supporting informed decisions.",
    situationIds: [
      "healthcare:patient-handover",
      "healthcare:case-conference",
      "healthcare:consent-discussion",
      "healthcare:service-escalation",
    ],
    defaultGoalIds: ["clarify", "reassure", "recommend"],
  },
];

export const seniorityLevels: readonly SeniorityLevel[] = [
  {
    id: "early-career",
    label: "Early career",
    description: "Building confidence in routine professional conversations and written updates.",
    communicationFocus: "State the situation clearly, ask focused questions, and confirm the next action.",
  },
  {
    id: "experienced-contributor",
    label: "Experienced contributor",
    description: "Owning specialised work and influencing colleagues without relying on formal authority.",
    communicationFocus: "Explain reasoning, surface trade-offs, and offer a practical recommendation.",
  },
  {
    id: "manager",
    label: "Manager",
    description: "Coordinating delivery, developing people, and translating decisions into team action.",
    communicationFocus: "Create alignment, give specific feedback, and make ownership unmistakable.",
  },
  {
    id: "senior-leader",
    label: "Senior leader",
    description: "Leading across functions and communicating decisions in uncertain or sensitive situations.",
    communicationFocus: "Frame the wider context, acknowledge risk, and set a clear direction.",
  },
  {
    id: "executive",
    label: "Executive",
    description: "Shaping enterprise priorities and communicating with boards, partners, and senior stakeholders.",
    communicationFocus: "Be concise, commercially grounded, and explicit about the decision required.",
  },
];

export const communicationGoals: readonly CommunicationGoal[] = [
  {
    id: "clarify",
    label: "Clarify a complex point",
    outcome: "The listener understands the issue, evidence, and implication without unnecessary detail.",
    coachingPrompt: "What is the one distinction your listener must understand?",
  },
  {
    id: "align",
    label: "Build alignment",
    outcome: "People leave with a shared interpretation of the priority, ownership, and next step.",
    coachingPrompt: "Which assumption or responsibility needs to become explicit?",
  },
  {
    id: "influence",
    label: "Influence a decision",
    outcome: "A recommendation feels credible, relevant, and easy to act on.",
    coachingPrompt: "What matters most to the decision-maker, and what evidence supports your case?",
  },
  {
    id: "recommend",
    label: "Make a recommendation",
    outcome: "The preferred course of action and its rationale are both unmistakable.",
    coachingPrompt: "Can you state your recommendation before explaining the supporting detail?",
  },
  {
    id: "negotiate",
    label: "Negotiate constructively",
    outcome: "Interests and constraints are explored without making the conversation adversarial.",
    coachingPrompt: "Which condition is essential, and where can you offer flexibility?",
  },
  {
    id: "challenge-diplomatically",
    label: "Challenge diplomatically",
    outcome: "A weak assumption or risky choice is questioned while trust remains intact.",
    coachingPrompt: "How can you challenge the idea without assigning blame to the person?",
  },
  {
    id: "coach",
    label: "Coach for improvement",
    outcome: "Feedback is specific, fair, and connected to an achievable next behaviour.",
    coachingPrompt: "What observable behaviour should continue or change next time?",
  },
  {
    id: "reassure",
    label: "Reassure with honesty",
    outcome: "Concern is acknowledged and confidence is supported without minimising real risk.",
    coachingPrompt: "What is known, what remains uncertain, and what is being done now?",
  },
];

export const professionalSituations: readonly ProfessionalSituation[] = [
  { id: "finance:month-end-close", roleId: "finance-accounting", label: "Month-end close", description: "Resolve balances, explain adjustments, and confirm the close position.", goalIds: ["clarify", "align"] },
  { id: "finance:variance-review", roleId: "finance-accounting", label: "Variance review", description: "Explain performance differences and distinguish timing from structural drivers.", goalIds: ["clarify", "challenge-diplomatically"] },
  { id: "finance:budget-forecast", roleId: "finance-accounting", label: "Budget and forecast", description: "Test assumptions and communicate the likely financial outlook.", goalIds: ["recommend", "influence"] },
  { id: "finance:audit-discussion", roleId: "finance-accounting", label: "Audit discussion", description: "Provide evidence and explain judgements to an internal or external reviewer.", goalIds: ["clarify", "reassure"] },

  { id: "project:roadmap-prioritisation", roleId: "project-product", label: "Roadmap prioritisation", description: "Compare opportunities and decide what should be delivered first.", goalIds: ["align", "influence"] },
  { id: "project:scope-change", roleId: "project-product", label: "Scope change", description: "Assess a requested change and agree its effect on time, cost, or quality.", goalIds: ["negotiate", "clarify"] },
  { id: "project:stakeholder-update", roleId: "project-product", label: "Stakeholder update", description: "Summarise progress, risks, decisions, and the next milestone.", goalIds: ["clarify", "reassure"] },
  { id: "project:delivery-retrospective", roleId: "project-product", label: "Delivery retrospective", description: "Learn from delivery without reducing the discussion to blame.", goalIds: ["coach", "challenge-diplomatically"] },

  { id: "technology:architecture-review", roleId: "technology-engineering", label: "Architecture review", description: "Evaluate a design against constraints, failure modes, and future needs.", goalIds: ["recommend", "challenge-diplomatically"] },
  { id: "technology:incident-response", roleId: "technology-engineering", label: "Incident response", description: "Coordinate recovery and communicate impact under pressure.", goalIds: ["align", "reassure"] },
  { id: "technology:code-review", roleId: "technology-engineering", label: "Code review", description: "Improve a change through specific, respectful technical feedback.", goalIds: ["coach", "challenge-diplomatically"] },
  { id: "technology:technical-interview", roleId: "technology-engineering", label: "Technical interview", description: "Explain an approach, test assumptions, and reason aloud.", goalIds: ["clarify", "influence"] },

  { id: "sales:discovery-call", roleId: "sales-business-development", label: "Discovery call", description: "Understand the customer’s problem, urgency, and decision process.", goalIds: ["clarify", "influence"] },
  { id: "sales:proposal-pitch", roleId: "sales-business-development", label: "Proposal pitch", description: "Connect an offer to measurable customer value.", goalIds: ["influence", "recommend"] },
  { id: "sales:objection-handling", roleId: "sales-business-development", label: "Objection handling", description: "Address concern without becoming defensive or dismissive.", goalIds: ["reassure", "negotiate"] },
  { id: "sales:pipeline-review", roleId: "sales-business-development", label: "Pipeline review", description: "Assess opportunity quality and agree the next commercial action.", goalIds: ["clarify", "challenge-diplomatically"] },

  { id: "people:performance-conversation", roleId: "people-human-resources", label: "Performance conversation", description: "Discuss expectations, evidence, and improvement respectfully.", goalIds: ["coach", "clarify"] },
  { id: "people:hiring-interview", roleId: "people-human-resources", label: "Hiring interview", description: "Assess capability consistently while giving the candidate a fair experience.", goalIds: ["clarify", "reassure"] },
  { id: "people:team-conflict", roleId: "people-human-resources", label: "Team conflict", description: "Surface different perspectives and restore a workable relationship.", goalIds: ["align", "challenge-diplomatically"] },
  { id: "people:organisational-change", roleId: "people-human-resources", label: "Organisational change", description: "Explain change honestly and help people understand what follows.", goalIds: ["reassure", "align"] },

  { id: "consulting:problem-framing", roleId: "consulting-strategy", label: "Problem framing", description: "Turn an ambiguous concern into a focused question and testable structure.", goalIds: ["clarify", "align"] },
  { id: "consulting:client-readout", roleId: "consulting-strategy", label: "Client readout", description: "Present evidence, implications, and outstanding questions succinctly.", goalIds: ["clarify", "influence"] },
  { id: "consulting:executive-recommendation", roleId: "consulting-strategy", label: "Executive recommendation", description: "Make a concise, evidence-based case for action.", goalIds: ["recommend", "influence"] },
  { id: "consulting:workshop-facilitation", roleId: "consulting-strategy", label: "Workshop facilitation", description: "Guide a group towards shared insight and concrete decisions.", goalIds: ["align", "challenge-diplomatically"] },

  { id: "operations:capacity-planning", roleId: "operations-supply-chain", label: "Capacity planning", description: "Balance expected demand with people, equipment, and time.", goalIds: ["recommend", "align"] },
  { id: "operations:supplier-negotiation", roleId: "operations-supply-chain", label: "Supplier negotiation", description: "Agree commercial and service conditions while protecting continuity.", goalIds: ["negotiate", "influence"] },
  { id: "operations:process-improvement", roleId: "operations-supply-chain", label: "Process improvement", description: "Diagnose wasted effort and establish a more reliable flow.", goalIds: ["clarify", "recommend"] },
  { id: "operations:disruption-response", roleId: "operations-supply-chain", label: "Disruption response", description: "Protect essential service and coordinate recovery from an interruption.", goalIds: ["align", "reassure"] },

  { id: "healthcare:patient-handover", roleId: "healthcare", label: "Patient handover", description: "Transfer essential clinical information and responsibility safely.", goalIds: ["clarify", "align"] },
  { id: "healthcare:case-conference", roleId: "healthcare", label: "Case conference", description: "Combine professional perspectives into a coordinated care plan.", goalIds: ["align", "recommend"] },
  { id: "healthcare:consent-discussion", roleId: "healthcare", label: "Consent discussion", description: "Explain options, benefits, and risks so a patient can decide freely.", goalIds: ["clarify", "reassure"] },
  { id: "healthcare:service-escalation", roleId: "healthcare", label: "Service escalation", description: "Raise a safety or capacity concern to the right decision-maker.", goalIds: ["recommend", "challenge-diplomatically"] },
];

export const professionalRoles: readonly ProfessionalRole[] = professionalRoleDefinitions.map(
  (role) => ({
    id: role.id,
    label: role.label,
    shortLabel: role.shortLabel,
    description: role.description,
    defaultGoalIds: role.defaultGoalIds,
    situations: professionalSituations.filter((situation) => situation.roleId === role.id),
  }),
);

const ALL_SENIORITY: readonly SeniorityLevelId[] = [
  "early-career",
  "experienced-contributor",
  "manager",
  "senior-leader",
  "executive",
];

const LEADERSHIP_SENIORITY: readonly SeniorityLevelId[] = ["manager", "senior-leader", "executive"];
const SPECIALIST_SENIORITY: readonly SeniorityLevelId[] = ["experienced-contributor", "manager", "senior-leader"];

export const professionalWords: readonly ProfessionalWord[] = [
  // Finance & Accounting
  {
    id: "finance-reconcile",
    term: "reconcile",
    partOfSpeech: "verb",
    pronunciation: "REK-uhn-syle",
    meaning: "To explain and resolve the difference between two sets of financial records.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["finance-accounting"],
    situations: ["finance:month-end-close", "finance:audit-discussion"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "reassure"],
    collocations: ["reconcile the balance", "reconcile to the ledger", "reconcile two reports"],
    example: "We reconciled the payroll report to the general ledger before closing the period.",
    whenToUse: "Use it when records should agree and you are describing the work needed to resolve a difference.",
    avoidOrMisuse: "Do not use it as a vague synonym for checking; reconciliation compares identifiable records or positions.",
    mission: "Explain one balance difference and say what you will reconcile it against.",
  },
  {
    id: "finance-variance",
    term: "variance",
    partOfSpeech: "noun",
    pronunciation: "VAIR-ee-uhns",
    meaning: "The difference between an actual result and a budget, forecast, or earlier result.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["finance-accounting", "operations-supply-chain"],
    situations: ["finance:variance-review", "finance:budget-forecast", "operations:capacity-planning"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["favourable variance", "unfavourable variance", "explain the variance"],
    example: "The revenue variance is mainly a timing issue rather than a loss of customer demand.",
    whenToUse: "Use it to name a measurable gap before explaining its underlying drivers.",
    avoidOrMisuse: "Always state what the result is being compared with; 'a variance exists' is rarely informative enough.",
    mission: "Describe a variance and separate its timing effect from its structural cause.",
  },
  {
    id: "finance-accrue",
    term: "accrue",
    partOfSpeech: "verb",
    pronunciation: "uh-KROO",
    meaning: "To recognise income or an expense in the period when it is earned or incurred, before cash moves.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["finance-accounting"],
    situations: ["finance:month-end-close", "finance:audit-discussion"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify"],
    collocations: ["accrue an expense", "accrued interest", "accrue over time"],
    example: "We accrued the consulting fee in June because the work was completed before the invoice arrived.",
    whenToUse: "Use it when explaining the accounting period in which an amount belongs.",
    avoidOrMisuse: "Do not say cash was accrued; cash is received or paid, while income, cost, or interest accrues.",
    mission: "Explain why one uninvoiced cost should be accrued this month.",
  },
  {
    id: "finance-material",
    term: "material",
    partOfSpeech: "adjective",
    pronunciation: "muh-TEER-ee-uhl",
    meaning: "Important enough to influence a financial decision or a reader’s understanding.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["finance-accounting", "consulting-strategy"],
    situations: ["finance:variance-review", "finance:audit-discussion", "consulting:executive-recommendation"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["material impact", "material misstatement", "material difference"],
    example: "The classification error is real, but it has no material effect on operating profit.",
    whenToUse: "Use it when significance depends on whether information could affect a decision.",
    avoidOrMisuse: "In finance, material means decision-relevant, not merely physical or noticeable.",
    mission: "State whether a reporting issue is material and give one reason.",
  },
  {
    id: "finance-substantiate",
    term: "substantiate",
    partOfSpeech: "verb",
    pronunciation: "suhb-STAN-shee-ayt",
    meaning: "To support a claim or accounting judgement with reliable evidence.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["finance-accounting", "consulting-strategy"],
    situations: ["finance:audit-discussion", "consulting:client-readout"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "influence"],
    collocations: ["substantiate a claim", "substantiate the estimate", "evidence to substantiate"],
    example: "The signed contracts substantiate management’s estimate of committed revenue.",
    whenToUse: "Use it when evidence must demonstrate that a statement or estimate is reasonable.",
    avoidOrMisuse: "Do not use it for simply explaining a claim; substantiation requires supporting evidence.",
    mission: "Name the evidence you would use to substantiate an important estimate.",
  },
  {
    id: "finance-run-rate",
    term: "run rate",
    partOfSpeech: "noun phrase",
    pronunciation: "RUN-rayt",
    meaning: "A current level of performance projected over a longer period, usually a year.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["finance-accounting", "sales-business-development"],
    situations: ["finance:budget-forecast", "sales:pipeline-review"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["clarify", "recommend"],
    collocations: ["annualised run rate", "current run rate", "cost run rate"],
    example: "At the current run rate, support costs will exceed the annual plan by September.",
    whenToUse: "Use it for a quick projection when the current pace is a reasonable starting point.",
    avoidOrMisuse: "Do not present a run rate as a forecast when seasonality or planned changes make the current pace misleading.",
    mission: "Use run rate to project one current cost, then state the projection’s limitation.",
  },
  {
    id: "finance-liquidity",
    term: "liquidity",
    partOfSpeech: "noun",
    pronunciation: "lih-KWID-ih-tee",
    meaning: "The availability of cash or assets that can quickly become cash to meet obligations.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["finance-accounting"],
    situations: ["finance:budget-forecast", "finance:audit-discussion"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["clarify", "reassure"],
    collocations: ["liquidity position", "liquidity risk", "preserve liquidity"],
    example: "Delaying the expansion would preserve liquidity during the seasonal fall in receipts.",
    whenToUse: "Use it when discussing the organisation’s ability to meet near-term payments.",
    avoidOrMisuse: "Liquidity is not the same as profitability; a profitable business can still run short of cash.",
    mission: "Explain one action that would strengthen the company’s liquidity position.",
  },
  {
    id: "finance-provision",
    term: "provision",
    partOfSpeech: "noun",
    pronunciation: "pruh-VIZH-uhn",
    meaning: "An amount recognised for a probable obligation whose timing or value is uncertain.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["finance-accounting"],
    situations: ["finance:month-end-close", "finance:audit-discussion"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["recognise a provision", "restructuring provision", "adequate provision"],
    example: "Management recognised a provision for the probable cost of settling the claim.",
    whenToUse: "Use it in accounting discussions about uncertain but probable obligations.",
    avoidOrMisuse: "Do not use provision as a general synonym for reserve; its accounting treatment has specific criteria.",
    mission: "Summarise why a probable obligation may require a provision.",
  },

  // Project & Product Management
  {
    id: "project-prioritise",
    term: "prioritise",
    partOfSpeech: "verb",
    pronunciation: "pry-OR-ih-tyze",
    meaning: "To decide which work is most important and should be done first.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["project-product", "operations-supply-chain", "technology-engineering"],
    situations: ["project:roadmap-prioritisation", "operations:capacity-planning", "technology:incident-response"],
    seniority: ALL_SENIORITY,
    goals: ["align", "recommend"],
    collocations: ["prioritise ruthlessly", "prioritise by impact", "prioritise competing requests"],
    example: "We should prioritise the onboarding problem because it affects every new customer.",
    whenToUse: "Use it when choices must be ordered rather than merely listed as important.",
    avoidOrMisuse: "Avoid saying that everything is a priority; prioritisation requires a meaningful sequence or exclusion.",
    mission: "Prioritise three requests and explain the criterion behind your first choice.",
  },
  {
    id: "project-scope",
    term: "scope",
    partOfSpeech: "noun",
    pronunciation: "SKOHP",
    meaning: "The agreed boundaries of what a project or piece of work will and will not include.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["project-product", "consulting-strategy", "technology-engineering"],
    situations: ["project:scope-change", "consulting:problem-framing", "technology:architecture-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "negotiate"],
    collocations: ["within scope", "out of scope", "scope the work"],
    example: "Automated migration is outside this release’s scope, but we can assess it for the next phase.",
    whenToUse: "Use it to make the boundaries of a commitment explicit.",
    avoidOrMisuse: "Do not use scope to dismiss a valid need without recording where or when it will be considered.",
    mission: "State one item that is in scope and one that is explicitly out of scope.",
  },
  {
    id: "project-trade-off",
    term: "trade-off",
    partOfSpeech: "noun",
    pronunciation: "TRAYD-off",
    meaning: "A choice in which gaining one benefit requires accepting a disadvantage elsewhere.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["project-product", "technology-engineering", "consulting-strategy"],
    situations: ["project:roadmap-prioritisation", "project:scope-change", "technology:architecture-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend", "negotiate"],
    collocations: ["make a trade-off", "explicit trade-off", "trade-off between speed and quality"],
    example: "The trade-off is a faster launch now versus lower maintenance effort later.",
    whenToUse: "Use it when a decision has competing benefits that cannot all be maximised.",
    avoidOrMisuse: "Do not call an avoidable failure a trade-off; the term implies a genuine choice between competing value.",
    mission: "Describe a current product trade-off without implying that either option is perfect.",
  },
  {
    id: "project-dependency",
    term: "dependency",
    partOfSpeech: "noun",
    pronunciation: "dih-PEN-duhn-see",
    meaning: "A person, task, system, or decision that another piece of work relies on.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["project-product", "technology-engineering", "operations-supply-chain"],
    situations: ["project:stakeholder-update", "technology:architecture-review", "operations:capacity-planning"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "align"],
    collocations: ["critical dependency", "external dependency", "manage dependencies"],
    example: "Legal approval is now the critical dependency for the planned launch date.",
    whenToUse: "Use it to identify something outside the task that can affect completion.",
    avoidOrMisuse: "Name the owner and timing; a long dependency list without action does not improve delivery.",
    mission: "Identify one critical dependency and ask its owner for a dated commitment.",
  },
  {
    id: "project-milestone",
    term: "milestone",
    partOfSpeech: "noun",
    pronunciation: "MYL-stohn",
    meaning: "A significant, verifiable point of progress in a project or plan.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["project-product", "operations-supply-chain"],
    situations: ["project:stakeholder-update", "project:roadmap-prioritisation", "operations:process-improvement"],
    seniority: ALL_SENIORITY,
    goals: ["align", "reassure"],
    collocations: ["reach a milestone", "key milestone", "milestone date"],
    example: "Completing the pilot with ten customers is the next milestone, not simply finishing the build.",
    whenToUse: "Use it for a meaningful checkpoint that demonstrates progress or enables a decision.",
    avoidOrMisuse: "Avoid labelling every small task a milestone; it should mark a significant outcome.",
    mission: "Turn one activity-based update into a measurable milestone statement.",
  },
  {
    id: "project-viable",
    term: "viable",
    partOfSpeech: "adjective",
    pronunciation: "VY-uh-buhl",
    meaning: "Capable of working successfully under the real constraints.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["project-product", "technology-engineering", "consulting-strategy"],
    situations: ["project:roadmap-prioritisation", "technology:architecture-review", "consulting:executive-recommendation"],
    seniority: ALL_SENIORITY,
    goals: ["recommend", "challenge-diplomatically"],
    collocations: ["commercially viable", "technically viable", "viable alternative"],
    example: "The concept is technically viable, but the support model is not yet commercially sustainable.",
    whenToUse: "Use it when judging whether an option can succeed in practice, not just in theory.",
    avoidOrMisuse: "State the relevant dimension; technically viable does not automatically mean affordable or desirable.",
    mission: "Assess whether one proposed feature is viable and name the decisive constraint.",
  },
  {
    id: "project-iterate",
    term: "iterate",
    partOfSpeech: "verb",
    pronunciation: "IT-uh-rayt",
    meaning: "To improve something through repeated cycles of testing, learning, and revision.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["project-product", "technology-engineering", "consulting-strategy"],
    situations: ["project:delivery-retrospective", "technology:code-review", "consulting:workshop-facilitation"],
    seniority: ALL_SENIORITY,
    goals: ["coach", "recommend"],
    collocations: ["iterate on the design", "test and iterate", "iterate quickly"],
    example: "We will iterate on the prototype after observing how users complete the first task.",
    whenToUse: "Use it when improvement will happen through an intentional learning cycle.",
    avoidOrMisuse: "Do not use iterate as a fashionable synonym for doing more work; name what feedback drives the next version.",
    mission: "Describe what you will test before you iterate on the current solution.",
  },
  {
    id: "project-roadmap",
    term: "roadmap",
    partOfSpeech: "noun",
    pronunciation: "ROHD-map",
    meaning: "A directional plan showing intended outcomes and their likely sequence over time.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["project-product", "technology-engineering"],
    situations: ["project:roadmap-prioritisation", "project:stakeholder-update", "technology:architecture-review"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["align", "influence"],
    collocations: ["product roadmap", "roadmap priority", "update the roadmap"],
    example: "The roadmap shows the outcomes we intend to pursue, not a guarantee of every delivery date.",
    whenToUse: "Use it to communicate direction and sequence across several initiatives.",
    avoidOrMisuse: "Do not present a roadmap as a fixed task schedule when priorities can change with evidence.",
    mission: "Explain one roadmap change by connecting it to a customer or business outcome.",
  },

  // Technology & Engineering
  {
    id: "technology-scalable",
    term: "scalable",
    partOfSpeech: "adjective",
    pronunciation: "SKAY-luh-buhl",
    meaning: "Able to handle substantial growth without a disproportionate loss of performance or rise in effort.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["technology-engineering", "operations-supply-chain"],
    situations: ["technology:architecture-review", "technology:technical-interview", "operations:capacity-planning"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["scalable architecture", "operationally scalable", "scale efficiently"],
    example: "The design is scalable for read traffic, but write contention remains a constraint.",
    whenToUse: "Use it when explaining how a system or process behaves as demand grows.",
    avoidOrMisuse: "Avoid calling something scalable without naming the growth dimension and limiting resource.",
    mission: "State what kind of growth your design can scale for and where it may struggle.",
  },
  {
    id: "technology-resilient",
    term: "resilient",
    partOfSpeech: "adjective",
    pronunciation: "rih-ZIL-yuhnt",
    meaning: "Able to continue operating or recover quickly when a component fails.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["technology-engineering", "operations-supply-chain"],
    situations: ["technology:architecture-review", "technology:incident-response", "operations:disruption-response"],
    seniority: ALL_SENIORITY,
    goals: ["recommend", "reassure"],
    collocations: ["resilient system", "operational resilience", "resilient to failure"],
    example: "The queue makes the service more resilient to brief interruptions in the downstream system.",
    whenToUse: "Use it when describing tolerance of failure and the ability to recover.",
    avoidOrMisuse: "Resilient does not mean failure-proof; explain the failure modes the design can and cannot absorb.",
    mission: "Explain how one design choice makes a service resilient to a named failure.",
  },
  {
    id: "technology-deprecate",
    term: "deprecate",
    partOfSpeech: "verb",
    pronunciation: "DEP-rih-kayt",
    meaning: "To discourage use of a technical feature because it will be replaced or removed.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["technology-engineering", "project-product"],
    situations: ["technology:architecture-review", "technology:code-review", "project:roadmap-prioritisation"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "align"],
    collocations: ["deprecate an API", "deprecated method", "deprecation notice"],
    example: "We will deprecate the legacy endpoint in October and support migration for two releases.",
    whenToUse: "Use it for a managed transition away from a technical capability that still exists temporarily.",
    avoidOrMisuse: "Do not say a feature is deprecated when it has already been removed; deprecation precedes removal.",
    mission: "Write a concise deprecation notice that includes the replacement and transition date.",
  },
  {
    id: "technology-refactor",
    term: "refactor",
    partOfSpeech: "verb",
    pronunciation: "ree-FAK-tuh",
    meaning: "To improve the internal structure of code without intentionally changing its behaviour.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["technology-engineering"],
    situations: ["technology:code-review", "technology:architecture-review", "technology:technical-interview"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend", "coach"],
    collocations: ["refactor the module", "safe refactoring", "refactor incrementally"],
    example: "I suggest we refactor the validation path first, then add the new rule behind tests.",
    whenToUse: "Use it when structural improvement is separate from adding visible behaviour.",
    avoidOrMisuse: "A rewrite or feature change is not automatically a refactor; the expected behaviour should remain stable.",
    mission: "Propose one small refactor and explain how you will prove behaviour is unchanged.",
  },
  {
    id: "technology-bottleneck",
    term: "bottleneck",
    partOfSpeech: "noun",
    pronunciation: "BOT-uhl-nek",
    meaning: "The part of a system that most limits its overall speed or capacity.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["technology-engineering", "operations-supply-chain"],
    situations: ["technology:architecture-review", "technology:incident-response", "operations:process-improvement"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["performance bottleneck", "identify the bottleneck", "remove a bottleneck"],
    example: "Database connection limits, not CPU, are the current bottleneck in checkout throughput.",
    whenToUse: "Use it after identifying the constraint that governs overall flow or performance.",
    avoidOrMisuse: "Do not label every slow component a bottleneck; only the binding constraint limits the whole system.",
    mission: "Name a suspected bottleneck and the measurement that would confirm it.",
  },
  {
    id: "technology-latency",
    term: "latency",
    partOfSpeech: "noun",
    pronunciation: "LAY-tuhn-see",
    meaning: "The delay between starting a request or action and receiving its response.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["technology-engineering"],
    situations: ["technology:architecture-review", "technology:incident-response", "technology:technical-interview"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["network latency", "reduce latency", "latency spike"],
    example: "Median latency is stable, but the slowest one per cent of requests now exceed two seconds.",
    whenToUse: "Use it when discussing response delay, ideally with a percentile and time unit.",
    avoidOrMisuse: "Do not confuse latency with throughput; one measures delay and the other measures volume over time.",
    mission: "Report a latency problem using a percentile, time unit, and likely customer impact.",
  },
  {
    id: "technology-idempotent",
    term: "idempotent",
    partOfSpeech: "adjective",
    pronunciation: "eye-dem-POH-tuhnt",
    meaning: "Producing the same intended result when the same operation is performed more than once.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["technology-engineering"],
    situations: ["technology:architecture-review", "technology:code-review", "technology:technical-interview"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["idempotent operation", "idempotency key", "make the request idempotent"],
    example: "The payment endpoint is idempotent, so retrying with the same key will not create a second charge.",
    whenToUse: "Use it when safe retries or repeated processing are important to a design.",
    avoidOrMisuse: "Idempotent does not mean read-only; an operation may change state once and still be safe to repeat.",
    mission: "Explain why one write operation should be idempotent and how you would achieve it.",
  },
  {
    id: "technology-rollback",
    term: "rollback",
    partOfSpeech: "noun",
    pronunciation: "ROHL-bak",
    meaning: "A return to a previous stable version or state after a change causes problems.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["technology-engineering", "project-product"],
    situations: ["technology:incident-response", "technology:architecture-review", "project:stakeholder-update"],
    seniority: ALL_SENIORITY,
    goals: ["align", "reassure"],
    collocations: ["initiate a rollback", "rollback plan", "safe rollback"],
    example: "Error rates doubled after the release, so we initiated a rollback while preserving the logs for analysis.",
    whenToUse: "Use it for the controlled reversal of a technical or operational change.",
    avoidOrMisuse: "As a verb, write 'roll back'; use the closed form 'rollback' as a noun or adjective.",
    mission: "Give a concise rollback decision with the trigger, owner, and immediate next step.",
  },

  // Sales & Business Development
  {
    id: "sales-qualify",
    term: "qualify",
    partOfSpeech: "verb",
    pronunciation: "KWOL-ih-fy",
    meaning: "To assess whether a prospective customer has a real need, fit, authority, and ability to buy.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["sales-business-development"],
    situations: ["sales:discovery-call", "sales:pipeline-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["qualify an opportunity", "well-qualified lead", "qualification criteria"],
    example: "We still need to qualify the opportunity by confirming the decision process and implementation budget.",
    whenToUse: "Use it when evaluating whether an opportunity deserves further sales effort.",
    avoidOrMisuse: "Do not treat qualification as interrogating the buyer; it should be a mutual assessment of fit.",
    mission: "Ask two respectful questions that would help qualify a new opportunity.",
  },
  {
    id: "sales-prospect",
    term: "prospect",
    partOfSpeech: "noun",
    pronunciation: "PROS-pekt",
    meaning: "A potential customer who may have a relevant need and could become a buyer.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["sales-business-development"],
    situations: ["sales:discovery-call", "sales:pipeline-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "influence"],
    collocations: ["qualified prospect", "prospect account", "engage a prospect"],
    example: "The prospect has a clear compliance problem, but the buying timeline is still uncertain.",
    whenToUse: "Use it for a potential buyer before a commercial relationship is established.",
    avoidOrMisuse: "Do not call an existing customer a prospect unless you mean a distinct new buying opportunity.",
    mission: "Summarise a prospect’s need, likely value, and one unresolved question.",
  },
  {
    id: "sales-value-proposition",
    term: "value proposition",
    partOfSpeech: "noun phrase",
    pronunciation: "VAL-yoo prop-uh-ZISH-uhn",
    meaning: "A clear explanation of why a customer should choose an offer and what valuable outcome it provides.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["sales-business-development", "project-product", "consulting-strategy"],
    situations: ["sales:proposal-pitch", "project:roadmap-prioritisation", "consulting:executive-recommendation"],
    seniority: ALL_SENIORITY,
    goals: ["influence", "recommend"],
    collocations: ["compelling value proposition", "articulate the value proposition", "customer value proposition"],
    example: "Our value proposition is faster regulatory reporting with fewer manual controls, not simply newer software.",
    whenToUse: "Use it to connect distinctive capability with a customer outcome.",
    avoidOrMisuse: "A feature list is not a value proposition; make the customer benefit and difference explicit.",
    mission: "State a value proposition in one sentence without using vague superlatives.",
  },
  {
    id: "sales-objection",
    term: "objection",
    partOfSpeech: "noun",
    pronunciation: "ub-JEK-shuhn",
    meaning: "A concern or reason a potential buyer gives for hesitating or declining.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["sales-business-development"],
    situations: ["sales:objection-handling", "sales:proposal-pitch"],
    seniority: ALL_SENIORITY,
    goals: ["reassure", "negotiate"],
    collocations: ["raise an objection", "address an objection", "price objection"],
    example: "Her objection is not the subscription price itself; it is the uncertainty around migration effort.",
    whenToUse: "Use it to identify a specific barrier that deserves exploration.",
    avoidOrMisuse: "Do not dismiss an objection as resistance; first clarify the concern and evidence behind it.",
    mission: "Acknowledge a customer objection and ask one question before responding to it.",
  },
  {
    id: "sales-conversion",
    term: "conversion",
    partOfSpeech: "noun",
    pronunciation: "kuhn-VUR-zhuhn",
    meaning: "The change from one stage of a commercial journey to a desired next stage or completed purchase.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["sales-business-development", "project-product"],
    situations: ["sales:pipeline-review", "sales:proposal-pitch", "project:roadmap-prioritisation"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["conversion rate", "improve conversion", "stage conversion"],
    example: "Demo-to-proposal conversion improved, but proposal-to-close conversion remains flat.",
    whenToUse: "Use it with a clearly defined starting point, target action, and time period.",
    avoidOrMisuse: "A conversion rate is ambiguous unless the two stages and measured population are named.",
    mission: "Describe one conversion rate precisely and suggest a plausible driver.",
  },
  {
    id: "sales-pipeline",
    term: "pipeline",
    partOfSpeech: "noun",
    pronunciation: "PYPE-lyne",
    meaning: "The set of active sales opportunities moving through defined stages towards a decision.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["sales-business-development"],
    situations: ["sales:pipeline-review", "sales:discovery-call"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["sales pipeline", "pipeline coverage", "pipeline quality"],
    example: "The pipeline appears large, but half of its value has no confirmed next meeting.",
    whenToUse: "Use it to discuss the quantity, quality, and movement of active opportunities.",
    avoidOrMisuse: "Do not equate total pipeline value with likely revenue; stage quality and probability matter.",
    mission: "Challenge one weak pipeline assumption using a specific piece of evidence.",
  },
  {
    id: "sales-retention",
    term: "retention",
    partOfSpeech: "noun",
    pronunciation: "rih-TEN-shuhn",
    meaning: "The ability to keep customers, revenue, or employees over a defined period.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["sales-business-development", "people-human-resources", "project-product"],
    situations: ["sales:pipeline-review", "people:organisational-change", "project:roadmap-prioritisation"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["clarify", "recommend"],
    collocations: ["customer retention", "retention rate", "improve retention"],
    example: "Improving first-month adoption is likely to have more impact on retention than another acquisition campaign.",
    whenToUse: "Use it when discussing how successfully a group remains over time.",
    avoidOrMisuse: "State whether you mean customers, revenue, or employees and define the measurement period.",
    mission: "Recommend one action to improve retention and identify the leading indicator you would watch.",
  },
  {
    id: "sales-upsell",
    term: "upsell",
    partOfSpeech: "verb",
    pronunciation: "UP-sel",
    meaning: "To help an existing customer choose a more valuable version or additional level of an offer.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["sales-business-development"],
    situations: ["sales:discovery-call", "sales:proposal-pitch", "sales:pipeline-review"],
    seniority: ALL_SENIORITY,
    goals: ["influence", "recommend"],
    collocations: ["upsell an existing customer", "upsell opportunity", "responsible upselling"],
    example: "We should only upsell the analytics package if the customer needs the additional reporting depth.",
    whenToUse: "Use it for expanding an existing purchase to a higher-value option.",
    avoidOrMisuse: "Do not treat upselling as pushing unnecessary features; it should follow a relevant customer need.",
    mission: "Frame an upsell around a genuine customer outcome rather than extra product features.",
  },

  // HR & People Leadership
  {
    id: "people-onboarding",
    term: "onboarding",
    partOfSpeech: "noun",
    pronunciation: "ON-bor-ding",
    meaning: "The structured process that helps a new employee become effective and connected.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["people-human-resources", "operations-supply-chain"],
    situations: ["people:hiring-interview", "people:organisational-change", "operations:process-improvement"],
    seniority: ALL_SENIORITY,
    goals: ["align", "reassure", "coach"],
    collocations: ["onboarding process", "new-hire onboarding", "improve onboarding"],
    example: "The revised onboarding gives each new manager a clear first-week decision and a named peer contact.",
    whenToUse: "Use it for the broader transition into a role, not only initial paperwork or orientation.",
    avoidOrMisuse: "Onboarding is not complete when forms are signed; it includes role clarity, access, relationships, and support.",
    mission: "Suggest one onboarding improvement that would help a new colleague contribute sooner.",
  },
  {
    id: "people-attrition",
    term: "attrition",
    partOfSpeech: "noun",
    pronunciation: "uh-TRISH-uhn",
    meaning: "A gradual reduction in employees or customers as people leave and are not replaced.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["people-human-resources", "operations-supply-chain"],
    situations: ["people:organisational-change", "people:performance-conversation", "operations:capacity-planning"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["clarify", "recommend"],
    collocations: ["employee attrition", "voluntary attrition", "attrition rate"],
    example: "Voluntary attrition is concentrated among experienced analysts rather than spread evenly across the function.",
    whenToUse: "Use it for measured loss from a population over time, especially in workforce planning.",
    avoidOrMisuse: "Avoid using attrition to depersonalise individual departures in sensitive employee conversations.",
    mission: "Describe an attrition pattern without assuming its cause, then propose one question to investigate.",
  },
  {
    id: "people-psychological-safety",
    term: "psychological safety",
    partOfSpeech: "noun phrase",
    pronunciation: "sy-kuh-LOJ-ih-kuhl SAYF-tee",
    meaning: "A shared belief that people can ask questions, admit mistakes, or disagree without humiliation or punishment.",
    difficulty: "c1",
    usefulness: "essential",
    learningMode: "active",
    roles: ["people-human-resources", "technology-engineering", "healthcare"],
    situations: ["people:team-conflict", "technology:incident-response", "healthcare:case-conference"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["coach", "reassure", "challenge-diplomatically"],
    collocations: ["create psychological safety", "low psychological safety", "psychologically safe team"],
    example: "Psychological safety improved when leaders thanked people for raising risks early rather than rewarding certainty.",
    whenToUse: "Use it when discussing whether team members feel able to speak candidly about work.",
    avoidOrMisuse: "It does not mean avoiding accountability or discomfort; respectful challenge is part of a safe team.",
    mission: "Name one leader behaviour that would increase psychological safety in a difficult meeting.",
  },
  {
    id: "people-equitable",
    term: "equitable",
    partOfSpeech: "adjective",
    pronunciation: "EK-wih-tuh-buhl",
    meaning: "Fair in a way that recognises different needs, circumstances, or barriers.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["people-human-resources", "healthcare"],
    situations: ["people:hiring-interview", "people:performance-conversation", "healthcare:case-conference"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend", "challenge-diplomatically"],
    collocations: ["equitable process", "equitable access", "equitable outcome"],
    example: "An equitable interview process gives every candidate the same core questions and any necessary accommodation.",
    whenToUse: "Use it when fairness may require more than giving everyone identical treatment.",
    avoidOrMisuse: "Do not use equitable as decoration; explain the barrier or need the approach is designed to address.",
    mission: "Explain one difference between an equal process and an equitable one in your workplace.",
  },
  {
    id: "people-mediate",
    term: "mediate",
    partOfSpeech: "verb",
    pronunciation: "MEE-dee-ayt",
    meaning: "To help people in disagreement reach understanding or an acceptable resolution as a neutral facilitator.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["people-human-resources", "project-product"],
    situations: ["people:team-conflict", "project:scope-change"],
    seniority: ["experienced-contributor", "manager", "senior-leader"],
    goals: ["align", "challenge-diplomatically"],
    collocations: ["mediate a dispute", "mediate between colleagues", "formal mediation"],
    example: "The HR partner mediated the discussion without deciding whose preferred solution should win.",
    whenToUse: "Use it when a neutral person supports communication between parties in conflict.",
    avoidOrMisuse: "A mediator facilitates resolution rather than imposing a decision or acting as one party’s advocate.",
    mission: "Open a mediated conversation by stating a neutral purpose and one ground rule.",
  },
  {
    id: "people-developmental-feedback",
    term: "developmental feedback",
    partOfSpeech: "noun phrase",
    pronunciation: "dih-vel-up-MEN-tuhl FEED-bak",
    meaning: "Specific feedback intended to help someone improve a skill or behaviour in future work.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["people-human-resources", "technology-engineering", "project-product"],
    situations: ["people:performance-conversation", "technology:code-review", "project:delivery-retrospective"],
    seniority: ["experienced-contributor", "manager", "senior-leader"],
    goals: ["coach", "reassure"],
    collocations: ["give developmental feedback", "specific feedback", "act on feedback"],
    example: "My developmental feedback is to state your recommendation earlier, before walking the audience through the analysis.",
    whenToUse: "Use it for future-focused guidance connected to an observable behaviour.",
    avoidOrMisuse: "Do not soften a performance decision by calling it developmental feedback; be honest about purpose and consequences.",
    mission: "Give one piece of developmental feedback with an observation and a practical next behaviour.",
  },
  {
    id: "people-succession-planning",
    term: "succession planning",
    partOfSpeech: "noun phrase",
    pronunciation: "suk-SESH-uhn PLAN-ing",
    meaning: "Preparing people and options to fill roles that may become critical or vacant.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "recognition",
    roles: ["people-human-resources"],
    situations: ["people:organisational-change", "people:performance-conversation"],
    seniority: LEADERSHIP_SENIORITY,
    goals: ["recommend", "align"],
    collocations: ["succession plan", "succession pipeline", "leadership succession"],
    example: "Our succession planning identifies two potential successors and the experience each still needs.",
    whenToUse: "Use it for deliberate preparation for future role continuity, especially in critical positions.",
    avoidOrMisuse: "A list of names is not a complete succession plan; readiness, development, and role risk also matter.",
    mission: "Describe one role continuity risk and a development action that could reduce it.",
  },
  {
    id: "people-engagement",
    term: "engagement",
    partOfSpeech: "noun",
    pronunciation: "en-GAYJ-muhnt",
    meaning: "The degree of commitment, energy, and connection people bring to their work and organisation.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["people-human-resources"],
    situations: ["people:organisational-change", "people:performance-conversation", "people:team-conflict"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "coach", "reassure"],
    collocations: ["employee engagement", "engagement score", "improve engagement"],
    example: "Engagement fell most sharply in teams where priorities changed without a clear explanation.",
    whenToUse: "Use it for a broader relationship with work, supported by behaviour or survey evidence.",
    avoidOrMisuse: "Do not infer engagement from enthusiasm alone; consider trust, intent to stay, effort, and voice.",
    mission: "Connect one engagement signal to a specific workplace condition without overstating causation.",
  },

  // Consulting & Strategy
  {
    id: "consulting-hypothesis",
    term: "hypothesis",
    partOfSpeech: "noun",
    pronunciation: "hy-POTH-uh-sis",
    meaning: "A provisional explanation or answer that can be tested with evidence.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["consulting-strategy", "technology-engineering", "project-product"],
    situations: ["consulting:problem-framing", "technology:incident-response", "project:delivery-retrospective"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["test a hypothesis", "working hypothesis", "hypothesis-driven"],
    example: "Our working hypothesis is that repeat contacts are rising because the first response does not resolve the underlying issue.",
    whenToUse: "Use it to make an uncertain explanation explicit and testable.",
    avoidOrMisuse: "Do not present a hypothesis as a conclusion; state what evidence would confirm or disprove it.",
    mission: "Turn one assumption into a testable hypothesis with a clear evidence check.",
  },
  {
    id: "consulting-synthesise",
    term: "synthesise",
    partOfSpeech: "verb",
    pronunciation: "SIN-thuh-size",
    meaning: "To combine information from several sources into a coherent insight or conclusion.",
    difficulty: "c1",
    usefulness: "essential",
    learningMode: "active",
    roles: ["consulting-strategy", "healthcare", "finance-accounting"],
    situations: ["consulting:client-readout", "healthcare:case-conference", "finance:variance-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["synthesise findings", "synthesise the evidence", "clear synthesis"],
    example: "We synthesised the interviews and service data into three recurring causes of delay.",
    whenToUse: "Use it when the work creates a new, coherent understanding from multiple inputs.",
    avoidOrMisuse: "Summarising sources separately is not synthesis; show the pattern or conclusion that connects them.",
    mission: "Synthesise three observations into one concise insight and its implication.",
  },
  {
    id: "consulting-benchmark",
    term: "benchmark",
    partOfSpeech: "noun",
    pronunciation: "BENCH-mark",
    meaning: "A relevant standard or comparison point used to assess performance.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["consulting-strategy", "finance-accounting", "operations-supply-chain"],
    situations: ["consulting:client-readout", "finance:variance-review", "operations:process-improvement"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["industry benchmark", "benchmark performance", "against the benchmark"],
    example: "Our resolution time is above the industry benchmark, although the case mix is more complex.",
    whenToUse: "Use it when a comparison helps interpret whether a result is strong, weak, or unusual.",
    avoidOrMisuse: "A benchmark is only useful when the comparison group, definition, and context are genuinely comparable.",
    mission: "Use a benchmark to assess performance, then name one comparability limitation.",
  },
  {
    id: "consulting-workstream",
    term: "workstream",
    partOfSpeech: "noun",
    pronunciation: "WURK-streem",
    meaning: "A coordinated group of related activities within a larger programme or project.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["consulting-strategy", "project-product"],
    situations: ["consulting:workshop-facilitation", "consulting:client-readout", "project:stakeholder-update"],
    seniority: ALL_SENIORITY,
    goals: ["align", "clarify"],
    collocations: ["lead a workstream", "workstream owner", "parallel workstreams"],
    example: "The data workstream will validate the baseline while the operating-model team interviews regional leaders.",
    whenToUse: "Use it to describe a distinct but coordinated body of work in a broader programme.",
    avoidOrMisuse: "Do not create a workstream label without a defined outcome, owner, and connection to the overall programme.",
    mission: "Define one workstream by its outcome, owner, and dependency on another team.",
  },
  {
    id: "consulting-actionable",
    term: "actionable",
    partOfSpeech: "adjective",
    pronunciation: "AK-shuh-nuh-buhl",
    meaning: "Specific and practical enough to support a clear decision or next action.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["consulting-strategy", "project-product", "people-human-resources"],
    situations: ["consulting:executive-recommendation", "project:delivery-retrospective", "people:performance-conversation"],
    seniority: ALL_SENIORITY,
    goals: ["recommend", "coach"],
    collocations: ["actionable insight", "actionable recommendation", "specific and actionable"],
    example: "The finding becomes actionable when we name the approval step, owner, and target date.",
    whenToUse: "Use it when information can realistically guide a decision or behaviour.",
    avoidOrMisuse: "Do not call a vague aspiration actionable; a person should be able to tell what to do next.",
    mission: "Rewrite one vague recommendation so that it becomes specific and actionable.",
  },
  {
    id: "consulting-triangulate",
    term: "triangulate",
    partOfSpeech: "verb",
    pronunciation: "try-ANG-gyuh-layt",
    meaning: "To compare several independent sources or methods to strengthen confidence in a conclusion.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["consulting-strategy", "finance-accounting", "healthcare"],
    situations: ["consulting:problem-framing", "consulting:client-readout", "healthcare:case-conference"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "challenge-diplomatically"],
    collocations: ["triangulate the findings", "triangulate data sources", "evidence triangulation"],
    example: "We triangulated customer interviews, complaint records, and call data before identifying the main failure point.",
    whenToUse: "Use it when independent evidence sources converge on or challenge the same conclusion.",
    avoidOrMisuse: "Simply collecting three sources is not triangulation; explain how they confirm, qualify, or contradict one another.",
    mission: "Name three independent sources you could triangulate to test a business claim.",
  },
  {
    id: "consulting-operating-model",
    term: "operating model",
    partOfSpeech: "noun phrase",
    pronunciation: "OP-uh-ray-ting MOD-uhl",
    meaning: "The way an organisation arranges people, processes, governance, and technology to deliver its strategy.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "recognition",
    roles: ["consulting-strategy", "operations-supply-chain", "people-human-resources"],
    situations: ["consulting:executive-recommendation", "operations:process-improvement", "people:organisational-change"],
    seniority: LEADERSHIP_SENIORITY,
    goals: ["clarify", "recommend", "align"],
    collocations: ["target operating model", "operating-model design", "redesign the operating model"],
    example: "The target operating model centralises policy but keeps customer decisions within regional teams.",
    whenToUse: "Use it when discussing how strategy will translate into repeatable organisational delivery.",
    avoidOrMisuse: "An organisation chart alone is not an operating model; decision rights, process, capability, and technology also matter.",
    mission: "Describe one operating-model choice and the behaviour it is meant to enable.",
  },
  {
    id: "consulting-executive-summary",
    term: "executive summary",
    partOfSpeech: "noun phrase",
    pronunciation: "ig-ZEK-yuh-tiv SUM-uh-ree",
    meaning: "A short, self-contained account of the main finding, implication, and recommended action.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["consulting-strategy", "finance-accounting", "project-product"],
    situations: ["consulting:executive-recommendation", "finance:budget-forecast", "project:stakeholder-update"],
    seniority: ["experienced-contributor", "manager", "senior-leader", "executive"],
    goals: ["clarify", "recommend", "influence"],
    collocations: ["concise executive summary", "write an executive summary", "one-page summary"],
    example: "The executive summary leads with the decision required, then gives the financial impact and principal risk.",
    whenToUse: "Use it for a time-constrained senior reader who needs the conclusion without reading the full analysis.",
    avoidOrMisuse: "Do not make it a contents list or vague introduction; it should stand alone and include the recommendation.",
    mission: "Write a three-sentence executive summary with finding, implication, and recommendation.",
  },

  // Operations & Supply Chain
  {
    id: "operations-throughput",
    term: "throughput",
    partOfSpeech: "noun",
    pronunciation: "THROO-put",
    meaning: "The amount of work, material, or transactions a process completes in a given time.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["operations-supply-chain", "technology-engineering"],
    situations: ["operations:capacity-planning", "operations:process-improvement", "technology:architecture-review"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["increase throughput", "daily throughput", "throughput constraint"],
    example: "Changing the packing sequence increased hourly throughput without adding another shift.",
    whenToUse: "Use it for completed volume per unit of time, with both units stated.",
    avoidOrMisuse: "Do not confuse throughput with inventory or capacity; it is the actual rate of completed flow.",
    mission: "Report a throughput change with a time unit and the process step that drove it.",
  },
  {
    id: "operations-lead-time",
    term: "lead time",
    partOfSpeech: "noun phrase",
    pronunciation: "LEED-tym",
    meaning: "The total time between requesting something and receiving or completing it.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["operations-supply-chain", "project-product"],
    situations: ["operations:supplier-negotiation", "operations:process-improvement", "project:stakeholder-update"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "negotiate"],
    collocations: ["supplier lead time", "reduce lead time", "average lead time"],
    example: "The supplier reduced lead time from six weeks to four by reserving production capacity.",
    whenToUse: "Use it for elapsed end-to-end time, defining the start and finish points.",
    avoidOrMisuse: "Lead time is not the same as hands-on processing time; waiting and transport may be included.",
    mission: "Define the lead time for one process and identify its largest waiting period.",
  },
  {
    id: "operations-capacity",
    term: "capacity",
    partOfSpeech: "noun",
    pronunciation: "kuh-PAS-ih-tee",
    meaning: "The maximum amount of work a team, system, or facility can handle in a period.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["operations-supply-chain", "project-product", "healthcare"],
    situations: ["operations:capacity-planning", "project:roadmap-prioritisation", "healthcare:service-escalation"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "align", "recommend"],
    collocations: ["available capacity", "capacity constraint", "increase capacity"],
    example: "The team has capacity for one urgent integration, so adding both would displace committed work.",
    whenToUse: "Use it to make the practical limit on work or service explicit.",
    avoidOrMisuse: "Do not treat nominal capacity as fully usable; maintenance, variability, and skill mix affect availability.",
    mission: "State a capacity constraint and the decision it forces this week.",
  },
  {
    id: "operations-contingency",
    term: "contingency",
    partOfSpeech: "noun",
    pronunciation: "kuhn-TIN-juhn-see",
    meaning: "A planned alternative or reserved resource for use if an expected risk occurs.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["operations-supply-chain", "project-product", "finance-accounting"],
    situations: ["operations:disruption-response", "project:stakeholder-update", "finance:budget-forecast"],
    seniority: ALL_SENIORITY,
    goals: ["reassure", "recommend"],
    collocations: ["contingency plan", "budget contingency", "activate the contingency"],
    example: "Our contingency is to shift urgent orders to the regional warehouse if the port remains closed tomorrow.",
    whenToUse: "Use it for a specific response prepared for a plausible uncertain event.",
    avoidOrMisuse: "A contingency is not a vague intention to cope; define the trigger, action, and owner.",
    mission: "Give a contingency plan with a clear activation trigger and named owner.",
  },
  {
    id: "operations-inventory-turnover",
    term: "inventory turnover",
    partOfSpeech: "noun phrase",
    pronunciation: "IN-vuhn-tree TURN-oh-vuh",
    meaning: "How often inventory is sold or used and replaced during a period.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["operations-supply-chain", "finance-accounting"],
    situations: ["operations:capacity-planning", "operations:process-improvement", "finance:variance-review"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["inventory-turnover ratio", "improve inventory turnover", "slow inventory turnover"],
    example: "Inventory turnover fell because demand shifted away from the older product range.",
    whenToUse: "Use it when evaluating how efficiently stock supports sales or production over time.",
    avoidOrMisuse: "Higher turnover is not always better if it creates shortages or emergency replenishment costs.",
    mission: "Explain one change in inventory turnover and its possible service consequence.",
  },
  {
    id: "operations-fulfilment",
    term: "fulfilment",
    partOfSpeech: "noun",
    pronunciation: "fuhl-FIL-muhnt",
    meaning: "The process of receiving, preparing, and completing a customer order.",
    difficulty: "upper-b2",
    usefulness: "high",
    learningMode: "active",
    roles: ["operations-supply-chain", "sales-business-development"],
    situations: ["operations:process-improvement", "operations:disruption-response", "sales:objection-handling"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "reassure"],
    collocations: ["order fulfilment", "fulfilment centre", "fulfilment delay"],
    example: "Order fulfilment is delayed by address validation, not by warehouse picking capacity.",
    whenToUse: "Use it for the end-to-end work required to complete an order or service commitment.",
    avoidOrMisuse: "Distinguish fulfilment from delivery when the process also includes allocation, picking, packing, or activation.",
    mission: "Explain where one fulfilment delay occurs and how customers are affected.",
  },
  {
    id: "operations-expedite",
    term: "expedite",
    partOfSpeech: "verb",
    pronunciation: "EK-spuh-dyte",
    meaning: "To make a process or delivery happen sooner by giving it special priority.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["operations-supply-chain", "project-product"],
    situations: ["operations:supplier-negotiation", "operations:disruption-response", "project:scope-change"],
    seniority: ALL_SENIORITY,
    goals: ["negotiate", "align"],
    collocations: ["expedite delivery", "expedite an order", "expediting fee"],
    example: "The supplier can expedite the replacement part, but we need approval for the additional freight cost.",
    whenToUse: "Use it when requesting or arranging faster-than-normal processing.",
    avoidOrMisuse: "Do not promise to expedite without confirming the cost, displaced work, and realistic new date.",
    mission: "Request that an urgent order be expedited while acknowledging the cost or trade-off.",
  },
  {
    id: "operations-service-level",
    term: "service level",
    partOfSpeech: "noun phrase",
    pronunciation: "SUR-vis LEV-uhl",
    meaning: "A defined measure of the speed, availability, or quality a service is expected to achieve.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["operations-supply-chain", "technology-engineering", "sales-business-development"],
    situations: ["operations:supplier-negotiation", "operations:disruption-response", "technology:incident-response"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "negotiate", "reassure"],
    collocations: ["agreed service level", "meet the service level", "service-level breach"],
    example: "We met the overall service level, but priority hospitals experienced longer delays than agreed.",
    whenToUse: "Use it with a defined metric, target, and measurement period.",
    avoidOrMisuse: "An average result can hide serious exceptions; explain the scope and distribution behind the service level.",
    mission: "State one service level precisely and report whether it was met.",
  },

  // Healthcare
  {
    id: "healthcare-triage",
    term: "triage",
    partOfSpeech: "verb",
    pronunciation: "TREE-ahzh",
    meaning: "To assess urgency and decide the order or level of attention cases require.",
    difficulty: "c1",
    usefulness: "essential",
    learningMode: "active",
    roles: ["healthcare", "technology-engineering", "operations-supply-chain"],
    situations: ["healthcare:patient-handover", "healthcare:service-escalation", "technology:incident-response"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "align"],
    collocations: ["triage a patient", "triage requests", "initial triage"],
    example: "The senior nurse triaged the referrals by clinical urgency rather than arrival time alone.",
    whenToUse: "Use it when cases must be assessed and prioritised according to urgency or impact.",
    avoidOrMisuse: "Triage is an initial prioritisation process, not a complete diagnosis or final resolution.",
    mission: "Explain the criteria you would use to triage three competing requests.",
  },
  {
    id: "healthcare-prognosis",
    term: "prognosis",
    partOfSpeech: "noun",
    pronunciation: "prog-NOH-sis",
    meaning: "The likely course and outcome of a medical condition.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "recognition",
    roles: ["healthcare"],
    situations: ["healthcare:case-conference", "healthcare:consent-discussion", "healthcare:patient-handover"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "reassure"],
    collocations: ["favourable prognosis", "long-term prognosis", "discuss the prognosis"],
    example: "The prognosis is generally favourable, although recovery time varies considerably between patients.",
    whenToUse: "Use it when discussing what is likely to happen over time, including uncertainty.",
    avoidOrMisuse: "Do not confuse prognosis with diagnosis; diagnosis identifies the condition, while prognosis concerns its likely course.",
    mission: "Explain a prognosis in plain language while acknowledging one important uncertainty.",
  },
  {
    id: "healthcare-contraindication",
    term: "contraindication",
    partOfSpeech: "noun",
    pronunciation: "kon-truh-in-dih-KAY-shuhn",
    meaning: "A condition or factor that makes a treatment or procedure inadvisable because it may cause harm.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["healthcare"],
    situations: ["healthcare:case-conference", "healthcare:consent-discussion", "healthcare:patient-handover"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "recommend"],
    collocations: ["absolute contraindication", "relative contraindication", "contraindication to treatment"],
    example: "Her recent bleeding is a contraindication to the standard anticoagulant, so the team is considering an alternative.",
    whenToUse: "Use it for a recognised reason not to use a particular intervention or to use it only with caution.",
    avoidOrMisuse: "A contraindication is stronger than a preference or inconvenience; distinguish absolute from relative risk.",
    mission: "Explain one contraindication and the alternative action it leads the team to consider.",
  },
  {
    id: "healthcare-adherence",
    term: "adherence",
    partOfSpeech: "noun",
    pronunciation: "ad-HEER-uhns",
    meaning: "How consistently a person follows an agreed treatment or care plan.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["healthcare"],
    situations: ["healthcare:case-conference", "healthcare:consent-discussion", "healthcare:patient-handover"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "coach", "reassure"],
    collocations: ["medication adherence", "support adherence", "barriers to adherence"],
    example: "Before describing her adherence as poor, we should ask whether cost or side effects are preventing regular use.",
    whenToUse: "Use it to discuss whether an agreed plan is being followed and what may support it.",
    avoidOrMisuse: "Avoid using adherence to blame the patient; explore access, understanding, preferences, and side effects.",
    mission: "Ask one non-judgemental question about a barrier to treatment adherence.",
  },
  {
    id: "healthcare-escalation",
    term: "escalation",
    partOfSpeech: "noun",
    pronunciation: "es-kuh-LAY-shuhn",
    meaning: "The act of raising a concern to a person or team with greater expertise or authority.",
    difficulty: "upper-b2",
    usefulness: "essential",
    learningMode: "active",
    roles: ["healthcare", "technology-engineering", "operations-supply-chain"],
    situations: ["healthcare:service-escalation", "technology:incident-response", "operations:disruption-response"],
    seniority: ALL_SENIORITY,
    goals: ["align", "recommend", "reassure"],
    collocations: ["clinical escalation", "escalation pathway", "prompt escalation"],
    example: "The drop in oxygen saturation meets the threshold for immediate clinical escalation.",
    whenToUse: "Use it when risk, urgency, or authority requires moving an issue to a higher level.",
    avoidOrMisuse: "Escalation should not sound punitive; state the risk, threshold, and support or decision required.",
    mission: "Make an escalation request that states the concern, evidence, and decision needed.",
  },
  {
    id: "healthcare-informed-consent",
    term: "informed consent",
    partOfSpeech: "noun phrase",
    pronunciation: "in-FORMD kuhn-SENT",
    meaning: "A person’s voluntary agreement after receiving understandable information about options, benefits, risks, and alternatives.",
    difficulty: "c1",
    usefulness: "essential",
    learningMode: "active",
    roles: ["healthcare"],
    situations: ["healthcare:consent-discussion", "healthcare:case-conference"],
    seniority: ALL_SENIORITY,
    goals: ["clarify", "reassure"],
    collocations: ["obtain informed consent", "valid consent", "consent process"],
    example: "The clinician checked understanding and discussed alternatives before asking for informed consent.",
    whenToUse: "Use it for a decision process in which information, capacity, understanding, and freedom from pressure matter.",
    avoidOrMisuse: "A signed form alone does not prove informed consent; the quality of the discussion is central.",
    mission: "Explain one treatment option in plain language and check understanding without leading the answer.",
  },
  {
    id: "healthcare-continuity-of-care",
    term: "continuity of care",
    partOfSpeech: "noun phrase",
    pronunciation: "kon-tih-NOO-uh-tee uhv KAIR",
    meaning: "Consistent, coordinated care across time, professionals, or services.",
    difficulty: "c1",
    usefulness: "high",
    learningMode: "active",
    roles: ["healthcare", "operations-supply-chain"],
    situations: ["healthcare:patient-handover", "healthcare:case-conference", "operations:process-improvement"],
    seniority: ALL_SENIORITY,
    goals: ["align", "reassure"],
    collocations: ["ensure continuity of care", "care continuity", "disrupt continuity"],
    example: "A named community contact will support continuity of care after the patient leaves hospital.",
    whenToUse: "Use it when care quality depends on reliable coordination across transitions or repeated contacts.",
    avoidOrMisuse: "Continuity does not always require the same clinician; information, ownership, and follow-up can provide it.",
    mission: "Identify one handover action that would protect continuity of care.",
  },
  {
    id: "healthcare-differential-diagnosis",
    term: "differential diagnosis",
    partOfSpeech: "noun phrase",
    pronunciation: "dif-uh-REN-shuhl dy-ag-NOH-sis",
    meaning: "A structured list of possible conditions that could explain a patient’s signs and symptoms.",
    difficulty: "c1",
    usefulness: "specialist",
    learningMode: "recognition",
    roles: ["healthcare"],
    situations: ["healthcare:case-conference", "healthcare:patient-handover"],
    seniority: SPECIALIST_SENIORITY,
    goals: ["clarify", "challenge-diplomatically", "recommend"],
    collocations: ["broad differential diagnosis", "narrow the differential", "include in the differential"],
    example: "The sudden onset keeps a vascular cause high in the differential diagnosis despite the normal initial scan.",
    whenToUse: "Use it when reasoning across plausible diagnoses before evidence supports a final conclusion.",
    avoidOrMisuse: "It is not a random list; possibilities should be relevant, prioritised, and connected to evidence or risk.",
    mission: "Present two plausible diagnoses and the finding that would help distinguish between them.",
  },
];

export function getProfessionalRole(roleId: ProfessionalRoleId): ProfessionalRole | undefined {
  return professionalRoles.find((role) => role.id === roleId);
}

export function getProfessionalSituation(
  situationId: ProfessionalSituationId,
): ProfessionalSituation | undefined {
  return professionalSituations.find((situation) => situation.id === situationId);
}

export function getProfessionalSituationsForRole(
  roleId: ProfessionalRoleId,
): ProfessionalSituation[] {
  return professionalSituations.filter((situation) => situation.roleId === roleId);
}

export function selectProfessionalWords(filters: ProfessionalWordFilters = {}): ProfessionalWord[] {
  return professionalWords.filter((entry) => {
    if (filters.roleId && !entry.roles.includes(filters.roleId)) return false;
    if (filters.situationId && !entry.situations.includes(filters.situationId)) return false;
    if (filters.seniorityId && !entry.seniority.includes(filters.seniorityId)) return false;
    if (filters.goalId && !entry.goals.includes(filters.goalId)) return false;
    if (filters.difficulty && entry.difficulty !== filters.difficulty) return false;
    if (filters.usefulness && entry.usefulness !== filters.usefulness) return false;
    if (filters.learningMode && entry.learningMode !== filters.learningMode) return false;
    return true;
  });
}

export function getProfessionalWord(id: string): ProfessionalWord | undefined {
  return professionalWords.find((entry) => entry.id === id);
}

/** @deprecated Prefer the standard `professionalWords` export. */
export const professionalVocabulary = professionalWords;

/** @deprecated Prefer `selectProfessionalWords`. */
export const selectProfessionalVocabulary = selectProfessionalWords;

/** @deprecated Prefer `getProfessionalWord`. */
export const getVocabularyEntry = getProfessionalWord;
